version: '3'
services:
    web:
        image: nginx:mainline-alpine3.18-perl
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf

    php:
        build: .
        develop:
            watch:
                - action: sync
                  path: ./app
                  target: ./app