version: '3'
services:
    php:
        depends_on:
            - composer
        container_name: "php-fpm"
        build: .
        volumes:
            - ./app:/app
        command: [sh, -c, "/app/vendor/bin/phpcs /app/src/ --colors -s --report-file='/app/phpcs-report.log'"]
        develop:
            watch:
                - action: sync
                  path: ./app
                  target: ./app

    composer:
        image: composer:2.7.1
        working_dir: /app
        command: [ "composer", "install" ]
        volumes:
            - ./app:/app